version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgresdb_dev
    environment: 
      POSTGRES_USER: luanadb
      POSTGRES_PASSWORD: jake_duskwood
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: filme-nest-api
    env_file: .env
    ports: 
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL_CONTAINER}
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:
